-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")

-- vim.api.nvim_create_autocmd("VimEnter", {
--   callback = function()
--     -- Open Copilot Chat
--     local width = 80
--     local height = 20
--     local buf = vim.api.nvim_create_buf(false, true) -- create a new buffer
--     local opts = {
--       relative = "editor",
--       width = width,
--       height = height,
--       col = (vim.o.columns - width) / 2,
--       row = (vim.o.lines - height) / 2,
--       anchor = "NW",
--       style = "minimal",
--     }
--     vim.api.nvim_open_win(buf, false, opts)
--     vim.cmd("CopilotChat")
--   end,
--   once = true,
-- })
